### ISSUE TITLE
`coremltools` v4.1 TensorFlow conversion attempt

### ISSUE THREAD

**Issue by SichangHe** [FedCampus/FedKit#20]
To install `coremltools` 4.1. This gymnastic is needed because old versions of Numpy could not be installed using new versions of Pip.

```sh
python3.8 -m pip install attr attrs ipython numpy packaging scipy sympy tensorflow tqdm
python3.8 -m pip install coremltools==4.1 --no-deps
python3.8 -m pip install 'protobuf<=3.21'
python3.8 -c 'from IPython import start_ipython;start_ipython()'
```

Branch: <https://github.com/SichangHe/FedCampus--FedKit/tree/use-coremltools-4-1>

Result running `python3.8 -m gen_mlmodel.mnist_eg.run`:

```python
WARNING:root:TensorFlow version 2.13.0 detected. Last version known to be fully compatible is 2.3.1 .
WARNING:root:Keras version 2.13.1 detected. Last version known to be fully compatible of Keras is 2.2.4 .
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 26, 26, 32)        320

 max_pooling2d (MaxPooling2  (None, 13, 13, 32)        0
 D)

 conv2d_1 (Conv2D)           (None, 11, 11, 32)        9248

 max_pooling2d_1 (MaxPoolin  (None, 5, 5, 32)          0
 g2D)

 flatten (Flatten)           (None, 800)               0

 dense (Dense)               (None, 500)               400500

 dense_1 (Dense)             (None, 10)                5010

=================================================================
Total params: 415078 (1.58 MB)
Trainable params: 415078 (1.58 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.8/3.8.18/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.8/3.8.18/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/sichanghe/AFileFolder/MonoRepo/FedKit/gen_mlmodel/mnist_eg/run.py", line 4, in <module>
    main()
  File "/Users/sichanghe/AFileFolder/MonoRepo/FedKit/gen_mlmodel/mnist_eg/__init__.py", line 52, in main
    mlmodel = convert(model)
  File "/Users/sichanghe/AFileFolder/MonoRepo/FedKit/gen_mlmodel/__init__.py", line 9, in convert
    return keras.convert(model)  # type: ignore
  File "/opt/homebrew/lib/python3.8/site-packages/coremltools/converters/keras/_keras_converter.py", line 807, in convert
    spec = _convert_to_spec(
  File "/opt/homebrew/lib/python3.8/site-packages/coremltools/converters/keras/_keras_converter.py", line 582, in _convert_to_spec
    from . import _keras2_converter
  File "/opt/homebrew/lib/python3.8/site-packages/coremltools/converters/keras/_keras2_converter.py", line 22, in <module>
    from . import _topology2
  File "/opt/homebrew/lib/python3.8/site-packages/coremltools/converters/keras/_topology2.py", line 17, in <module>
    _keras.layers.advanced_activations.LeakyReLU,
AttributeError: module 'keras.layers' has no attribute 'advanced_activations'
```

**Comment by SichangHe** [comment]
The above was run on my M1 MacBook, which does not have Keras 2.2.4 support. I tried it on the Debian server as well but could not get Numpy actually working.

@Johnnybyzhang, can I have a Docker container of environment from March, 2021?

**Comment by SichangHe** [comment]
The thing is I would probably need an older pip. Maybe an old Conda would also work.

**Comment by SichangHe** [comment]
This looks like a likely docker image: https://hub.docker.com/r/continuumio/conda-ci-linux-64-python3.8, @Johnnybyzhang.

Edit: I tried running this image but it just exits immediately.

**Comment by SichangHe** [comment]
The Dockerfile works, but I cannot get a shell.

**Comment by SichangHe** [comment]
Somehow, on x86_64 Debian, I still get `/opt/conda/bin/python3: /opt/conda/bin/python3: cannot execute binary file`.

**Comment by SichangHe** [comment]
Somehow, on x86_64 Debian, I still get `/opt/conda/bin/python3: /opt/conda/bin/python3: cannot execute binary file`.

**Comment by SichangHe** [comment]
No longer needed. Latest version work as well.
